### ISSUE TITLE
performance and how to use?

### ISSUE THREAD

**Issue by Jasperty** [loveritsu929/4080-RLforQA#1]

**Comment by loveritsu929** [comment]
I'm still working on designing the rl agent. Currently, I'm just playing with the dataset and BERT sentence embedding [https://github.com/hanxiao/bert-as-service]

**Comment by Jasperty** [comment]
> I'm still working on designing the rl agent. Currently, I'm just playing with the dataset and BERT sentence embedding [https://github.com/hanxiao/bert-as-service]

i also work on hotpot with bert for answer sentence classification, but i get a worse result, so i would like to know what your result is
